### PR TITLE
Change the "transaction failed"

### PR DESCRIPTION
**Pull request by MerlinEgalite**

### CODE REVIEW

**Review by mendesfabio — COMMENTED** [review]
@MerlinEgalite, should we add target blank to this link?

**Comment by mendesfabio** [comment]
Actually, I also forgot to add the target blank to the other links in the DonateModal. Could you fix those?

**Comment by tamarandom** [comment]
@mendesfabio who are you asking? ;)

**Comment by MerlinEgalite** [comment]
I think it's better @mendesfabio but what are your thoughts about that?
And yes if you want i can change the other ;)

**Comment by mendesfabio** [comment]
I agree with you, @MerlinEgalite. Feel free to fix the other links too.

**Review by mendesfabio — APPROVED** [review]
LGTM! thanks, @MerlinEgalite!

**Pull request merged**
